### ISSUE TITLE
New member registrations failed to submit

### ISSUE THREAD

**Issue by yuanzhou** [sennetconsortium/member-ui#16]
Joe Bisciotti reached out with the following failed registrations:

Happened on 1/2/2024:
>I am Mythili Dileepan from Dr. David Bernlohr's lab, University of Minnesota. I am going to work on the adipose tissue/SenNet project. I tried to register on SenNet but I couldn't. Could you please help me with it?

Happened on 12/19/2023:
>This is Li Xia from University of Rochester Medical Center. I just submitted my registration online as a new user. But I failed to submit it. Thank you for helping me to solve this problem. Let me know if you need more information.

**Comment by yuanzhou** [comment]
```
[2024-01-02 19:50:51] INFO in app: =========== New Registration POSTed of globus_user_id b94b699c-3fb2-47b0-99f8-d52284965c8d ===========
Failed to add new stage user, something wrong with add_new_stage_user()
[Errno 2] No such file or directory: '/backup/sennet-profile-pics/b94b699c-3fb2-47b0-99f8-d52284965c8d.png'
```

I've reached out to @humadragonbane to confirm the missing profile pics directory on SenNet WP and Registration PROD VM.

**Comment by yuanzhou** [comment]
The profile images directory used for new registration may have been deleted accidentally. @humadragonbane has recovered it and I've also set the correct file permission. Will need to ask @jbisciotti to reach out to the two members and re-submit the registrations to find out.

**Comment by jbisciotti** [comment]
Received confirmation from Mythili that they were able to register with no issue!

**Comment by jbisciotti** [comment]
And received confirmation from Li--should be all set! Thanks Zhou!

**Comment by yuanzhou** [comment]
Thanks @jbisciotti! Jesse probably showed you this, you can login to https://profile.sennetconsortium.org/registrations/ and process or deny new registrations from there if you have the Admin access. There are a lot pending registrations as I can tell, please reach out to Kay if you have questions about the members.
