### ISSUE TITLE
reCAPTCHA broken in registration sing-up form

### ISSUE THREAD

**Issue by yuanzhou** [sennetconsortium/member-ui#18]
Forwarded by @jbisciotti on 1/26/2024:

>My name is Sean Donahue.  I'm a developer with Matt Ruffalo's group of the HuBMAP HIVE/CODCC.  I was recently trying to sign up for access to Sennett Consortium resources and encountered a broken Captcha on the signup form, screenshot attached.  Please let me know when this issue is resolved so that I can complete the registration and gain access to the resources I need.

![Screenshot from 2024-01-26 09-16-17](https://github.com/sennetconsortium/member-ui/assets/195873/27c33c26-0568-4881-89a4-6ee25732244e)

**Comment by humadragonbane** [comment]
google recaptcha keys on the server updated

reaching out to Joe @jbisciotti

**Comment by humadragonbane** [comment]
Joe Biscotti confirms this is working now
