### ISSUE TITLE
Migrate WP site and Registration from HuBMAP VMs to SenNet VMs

### ISSUE THREAD

**Issue by yuanzhou** [sennetconsortium/member-ui#8]

**Comment by humadragonbane** [comment]
wp_dev sennet instance stood up
ssh -v -i "sennet_dev.pem" ec2-user@18.215.51.199

selinux disabled
php8 / python3.9/ uwsgi (epel) installed 
nginx config files scp
wp sennet config files scp

new dns 
[wp-new.dev.sennetconsortium.org](https://wp-new.dev.sennetconsortium.org/)  502 Bad Gateway Error currently
[profile-new.dev.sennetconsortium.org](https://profile-new.dev.sennetconsortium.org/)  502 Bad Gateway Error currently

needs new certs generated

**Comment by yuanzhou** [comment]
@humadragonbane have you verified the S3 backup and are we having a daily backup?

**Comment by humadragonbane** [comment]
@yuanzhou Backups for sennet prod wordpress server are as follows.

daily backup at 7am 
backups synced to S3 bucket @7:30
S3 Bucket: `sennet-wp-backup-bucket`

```
# Backup the SenNet wordpress database and wp-site directory
0 7 * * * /opt/sennet/backup_scripts/backup-wp.sh >/dev/null 2>&1

# Backup the main nginx configuration file
0 6 * * * tar -czf /tmp/nginx-conf/nginx.conf-`date +"%Y-%m-%d-%H-%M-%S"`.tar.gz -C /etc/nginx/ nginx.conf >/dev/null 2>&1

# Backup the nginx application-specific configuration directory
0 6 * * * tar -czf /tmp/nginx-conf/conf.d-`date +"%Y-%m-%d-%H-%M-%S"`.tar.gz -C /etc/nginx/ conf.d >/dev/null 2>&1

# Copy Backups to S3 Bucket   -- use sync instead of cp to sync just new content to the bucket
0 7 30 * * /usr/local/bin/aws s3 sync /backup s3://sennet-wp-backup-bucket --region us-east-1
```
